name: "TEST - Matrix Data Passing"

on:
  push:


jobs:
  # ETAPA 1: SIMULAR o trabalho da matriz que cria dois arquivos diferentes.
  simulate-fetch-rpms:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gpu-driver: [true, false]
    outputs:
      result: ${{ steps.export-result.outputs.result }}

    steps:
      - name: Prepare dynamic variables
        id: prep
        run: |
          if [[ "${{ matrix.gpu-driver }}" == "true" ]]; then
            echo "output_file=os-updates.yaml" >> $GITHUB_OUTPUT
          else
            echo "output_file=os-updates--no-gpu.yaml" >> $GITHUB_OUTPUT
          fi

      - name: Create dummy YAML file content
        run: |
          if [[ "${{ matrix.gpu-driver }}" == "true" ]]; then
            # Conteúdo para os-updates.yaml
            cat << 'EOF' > ${{ steps.prep.outputs.output_file }}
updates:
  - name: kernel-default
    version: 6.4.0
  - name: xz
    version: 5.4.3
EOF
          else
            # Conteúdo para os-updates--no-gpu.yaml
            cat << 'EOF' > ${{ steps.prep.outputs.output_file }}
updates:
  - name: coreutils
    version: "9.4"
    version: 1.14.93
  - name: zypper-needs-restarting
    version: 1.14.93
EOF
          fi

      - name: Verify file was created in this matrix job
        run: |
          echo "Arquivo criado nesta execução da matriz:"
          ls -l ${{ steps.prep.outputs.output_file }}

      - name: Encode file and set as output
        id: export-result
        run: |
          ENCODED_STRING=$(base64 -w 0 ${{ steps.prep.outputs.output_file }})
          JSON_PAYLOAD=$(jq -cn --arg name "${{ steps.prep.outputs.output_file }}" --arg content "$ENCODED_STRING" '{file_name: $name, file_content_base_64: $content}')
          echo "result=$JSON_PAYLOAD" >> $GITHUB_OUTPUT
          
  # ETAPA 2: O TRABALHO "COLETOR". Ele espera por TODOS os trabalhos da matriz,
  # em seguida, combina com segurança suas saídas em um único array JSON limpo.
  combine-outputs:
    runs-on: ubuntu-latest
    needs: simulate-fetch-rpms
    outputs:
      all_results: ${{ steps.combine.outputs.json_string }}
    steps:
      - name: Combine matrix outputs into a single JSON array
        id: combine
        run: |
          echo "Recebendo o objeto de saídas da matriz bruta:"
          echo '${{ toJSON(needs.simulate-fetch-rpms.outputs) }}'
          
          # Esta é a etapa mágica que limpa os dados
          JSON_STRING=$(echo '${{ toJSON(needs.simulate-fetch-rpms.outputs) }}' | jq -c '[.result[] | fromjson]')
          
          echo "--------------------------------------------------"
          echo "Array JSON combinado e limpo que será passado adiante:"
          echo "$JSON_STRING"
          
          echo "json_string=$JSON_STRING" >> $GITHUB_OUTPUT

  # ETAPA 3: SIMULAR o trabalho que precisa receber os dados.
  # Ele depende do trabalho coletor, não diretamente do trabalho da matriz.
  simulate-create-pr:
    runs-on: ubuntu-latest
    needs: combine-outputs
    steps:
      - name: Restore YAML files from combined output
        run: |
          echo "--- Iniciando a restauração de arquivos a partir da saída combinada ---"

          echo "[Passo 1/2] Obtendo o array JSON combinado do trabalho 'combine-outputs'..."
          OUTPUTS_JSON='${{ needs.combine-outputs.outputs.all_results }}'
          echo "Array JSON combinado recebido:"
          echo "$OUTPUTS_JSON"
          echo "--------------------------------------------------"

          echo "[Passo 2/2] Extraindo, decodificando e verificando os arquivos..."
          GPU_B64=$(echo "$OUTPUTS_JSON" | jq -r '.[] | select(.file_name=="os-updates.yaml") | .file_content_base_64')
          NOGPU_B64=$(echo "$OUTPUTS_JSON" | jq -r '.[] | select(.file_name=="os-updates--no-gpu.yaml") | .file_content_base_64')

          if [[ -z "$GPU_B64" ]] || [[ -z "$NOGPU_B64" ]]; then
            echo "::error:: FALHA ao extrair o conteúdo de um ou ambos os arquivos YAML."
            exit 1
          fi

          echo "Decodificando e criando arquivos..."
          echo "$GPU_B64" | base64 --decode > os-updates.yaml
          echo "$NOGPU_B64" | base64 --decode > os-updates--no-gpu.yaml

          echo "--------------------------------------------------"
          echo "VERIFICAÇÃO FINAL: Ambos os arquivos foram restaurados com sucesso!"
          ls -l os-updates*.yaml
          
          echo -e "\n--- Conteúdo de os-updates.yaml ---"
          cat os-updates.yaml
          
          echo -e "\n--- Conteúdo de os-updates--no-gpu.yaml ---"
          cat os-updates--no-gpu.yaml